### PR TITLE
Jan 2019 testfix

### LINKED ISSUE #21: December Update for review
Suggestions 
 - Update screenshots 
 - Take advantage of DDoS feature (WDS & Lab)
 - Use Azure Firewall (WDS & Lab)
 - Virtual Network Service Endpoints
 - Update for new features of ExpressRoute (WDS)

### PR DESCRIPTION
**Pull request by DawnmarieDesJardins**
This PR will resolve #21

### CODE REVIEW

**Comment by mwasham** [comment]
ready

**Comment by DawnmarieDesJardins** [comment]
@mwasham @Jeff-Opsgility 
Before we can merge:  (email with screenshots sent to you)
Please archive the unguided lab (it looks like it was updated).
Exercise 5, Task 1, number 2 - please verify indenting & numbering
Exercise 7, Task 4 - images are not showing up in doc outside of MD

**Comment by mwasham** [comment]
Hmm.. 
the unguided lab is already in archive
Exercise 5 looks ok to me?
Exercise 7 the images show for me?
Ping me later and I can see what you're seeing..

**Comment by mwasham** [comment]
ok - fixed

**Pull request merged**
